---

- name: Uplift LDAP
  hosts: ldap
  become: yes
  tasks:
    - name: Run uplift
      run_once: yes
      block:
        - name: Set facts
          set_fact:
            workspace: '/root/uplift/{{ ldap_config.rbac_version }}'
            ssm_prefix: '/{{ environment_name }}/{{ project_name }}/apacheds/apacheds/'

        - name: Ensure LDAP service is running so we can take a backup
          service:
            name: slapd
            state: started

        - name: Backup the data to S3
          shell: backup_ldap

        - name: Create context entries
          include: create_context.yml

        - name: Import policies
          include: import_policies.yml

        - name: Import schemas
          include: import_schemas.yml

        - name: Import roles
          include: import_roles.yml

        - name: Import users/clients
          include: import_users.yml

        - name: Remove workspace
          file:
            path: '{{ workspace }}'
            state: absent