---

- name: Uplift LDAP
  hosts: ldap
  become: yes
  tasks:
    - name: Checkout the configured RBAC version
      # `ldap_config.rbac_version` is defined per environment in the hmpps-env-configs repo
      delegate_to: localhost
      run_once: yes
      become: no
      git:
        repo: https://github.com/ministryofjustice/hmpps-ndelius-rbac
        dest: '{{ ldap_config.rbac_version }}'
        version: '{{ ldap_config.rbac_version }}'

    - name: Run uplift
      run_once: yes
      include_tasks: '{{ ldap_config.rbac_version }}/import_all.yml'